name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test test/qa_tests/
        continue-on-error: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

#      - name: Upload test videos
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-videos
#          path: test-results/
#          retention-days: 7

      - name: Create issue on test failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            // Check if there's already an open issue for test failures
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'playwright-test-failure'
            });
            
            const existingIssue = issues.data.find(issue => 
              issue.title.includes('Playwright Tests Failed')
            );
            
            const issueBody = `## 🚨 Playwright Tests Failed
            
            **Workflow Run:** [View Details](${runUrl})
            **Branch:** \`${context.ref}\`
            **Commit:** ${context.sha.substring(0, 7)}
            **Triggered by:** ${context.actor}
            
            ### Details
            The Playwright test suite has failed. Please check the workflow run for detailed test results, screenshots, and videos.
            
            **Artifacts:**
            - Test reports and videos are available in the workflow run artifacts
            
            ---
            *This issue was automatically created by GitHub Actions*`;
            
            if (existingIssue) {
              // Add a comment to existing issue
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: existingIssue.number,
                body: `Another test failure occurred:\n\n${issueBody}`
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🚨 Playwright Tests Failed',
                body: issueBody,
                labels: ['playwright-test-failure', 'bug', 'automated']
              });
            }